project:
  type: website
  output-dir: "docs"

website:
  title: "UNICEF Education Completion: Story & Visualisations"
  navbar:
    left:
      - ""
format:
    html:
      theme: cosmo
      toc: true
      embed-resources: true
      code-fold: true
execute:
  echo: true
  warning: false

